### PR TITLE
Fix crosses initialization

### PR DESCRIPTION
**Pull request by sabas1080**
Hi @jpmeijers 

I found an error compiling with platformio "crosses initialization" apparently within switch can not declare locally received

Thanks

### CODE REVIEW

**Comment by jwillemsen** [comment]
Making received global is way to much scope, working on issue #26 which also shows this, let me test another fix using travis-ci.

**Comment by jwillemsen** [comment]
PR #27 has a different fix which doesn't result in a bigger scope. Added also the first travis-ci integration configuration, waiting on a response from platformio.org for the sodaq boards

**Comment by jpmeijers** [comment]
Closing because @jwillemsen has a better fix in PR #27

**Comment by sabas1080** [comment]
Thanks, excelent work

**Pull request closed without merging**
