### PR TITLE
Add github action based CI

### PR DESCRIPTION
**Pull request by jwillemsen**

### CODE REVIEW

**Review by jpmeijers — APPROVED** [review]
Wow this is great!

**Comment by jwillemsen** [comment]
Maybe remove the travis-ci integration, that doesn't have any additional value, what do you want todo @jpmeijers

**Comment by jpmeijers** [comment]
Yes, absolutely. No reason to have both.

**Comment by jpmeijers** [comment]
I actually don't know how to remove it. Can you help @jwillemsen?

**Comment by jwillemsen** [comment]
Removing the .travis.yml is enough, I have resolved the merge conflict

**Pull request merged**
